---
title: "Arima"
author: "Skalin Ivan"
output: html_document
---
## Load and Process Data

```{r}
eps <- scan("./jj.dat")
eps_ts <- ts(eps, start = c(1960, 1), frequency = 4)
```

## Plot Quarterly EPS

```{r}
plot(eps_ts,
     main = "Quarterly EPS for Johnson & Johnson (1960-1980)",
     xlab = "Time",
     ylab = "EPS",
     col = "blue",
     lwd = 2)
```

## First Differencing

```{r}
eps_diff <- diff(eps_ts)
plot(eps_diff,
     main = "First Difference of EPS",
     xlab = "Time",
     ylab = "Difference in EPS",
     col = "darkgreen",
     lwd = 2)
```

## Log Transformation

```{r}
eps_log <- log10(eps_ts)
plot(eps_log,
     main = "Log10 of Quarterly EPS",
     xlab = "Time",
     ylab = "log10(EPS)",
     col = "purple",
     lwd = 2)
```

## Differenced Log Transformation

```{r}
eps_log_diff <- diff(eps_log)
plot(eps_log_diff,
     main = "First Difference of log10(EPS)",
     xlab = "Time",
     ylab = "Difference in log10(EPS)",
     col = "brown",
     lwd = 2)
```

## ACF and PACF Analysis

```{r}
acf(eps_log_diff, main = "ACF of Differenced log10(EPS)")
# I think as we can see as 0.25 lag is over -0.5 it may be overdifferentiated
pacf(eps_log_diff, main = "PACF of Differenced log10(EPS)")
```

## ARIMA Modeling

```{r}
# Now we treat this as stationary, using d = 0 as it doesn’t need further differencing
model0 <- arima(eps_log, order = c(0, 0, 0))
model0 # Autoregressive Integrated Moving Average

# p and q represent the number of terms, not lag difference
model1 <- arima(eps_log, order = c(1, 0, 0))
model2 <- arima(eps_log, order = c(0, 0, 1))
model3 <- arima(eps_log, order = c(1, 0, 1))

# Compare AIC values
aic_values <- c(model1$aic, model2$aic, model3$aic)
names(aic_values) <- c("ARIMA(1,0,0)", "ARIMA(0,0,1)", "ARIMA(1,0,1)")
print(aic_values)
```

## Simulating AR Processes

```{r}
set.seed(123)
```

### AR(1)
```{r}
ts.sim_AR1 <- arima.sim(n = 10000, list(ar = c(0.9)))
plot(ts.sim_AR1, main = "Simulated AR(1) Process", col = "darkred")
acf(ts.sim_AR1, main = "ACF of AR(1) Process")
pacf(ts.sim_AR1, main = "PACF of AR(1) Process")
```

### AR(2)
```{r}
ts.sim_AR2 <- arima.sim(n = 10000, list(ar = c(0.9, -0.5)))
plot(ts.sim_AR2, main = "Simulated AR(2) Process", col = "darkred")
acf(ts.sim_AR2, main = "ACF of AR(2) Process")
pacf(ts.sim_AR2, main = "PACF of AR(2) Process")
```

### AR(3)
```{r}
ts.sim_AR3 <- arima.sim(n = 10000, list(ar = c(0.9, -0.5, 0.2)))
plot(ts.sim_AR3, main = "Simulated AR(3) Process", col = "darkred")
acf(ts.sim_AR3, main = "ACF of AR(3) Process")
pacf(ts.sim_AR3, main = "PACF of AR(3) Process")
```

### AR(4)
```{r}
ts.sim_AR4 <- arima.sim(n = 10000, list(ar = c(0.9, -0.5, 0.2, -0.3)))
plot(ts.sim_AR4, main = "Simulated AR(4) Process", col = "darkred")
acf(ts.sim_AR4, main = "ACF of AR(4) Process")
pacf(ts.sim_AR4, main = "PACF of AR(4) Process")
```

## Simulating MA Processes

### MA(1)
```{r}
ts.sim_MA1 <- arima.sim(n = 10000, list(ma = c(-1.9)))
plot(ts.sim_MA1, main = "Simulated MA(1) Process", col = "blue")
acf(ts.sim_MA1, main = "ACF of MA(1) Process")
pacf(ts.sim_MA1, main = "PACF of MA(1) Process")
```

### MA(2)
```{r}
ts.sim_MA2 <- arima.sim(n = 10000, list(ma = c(-1.9, 1.7)))
plot(ts.sim_MA2, main = "Simulated MA(2) Process", col = "blue")
acf(ts.sim_MA2, main = "ACF of MA(2) Process")
pacf(ts.sim_MA2, main = "PACF of MA(2) Process")
```

### MA(3)
```{r}
ts.sim_MA3 <- arima.sim(n = 10000, list(ma = c(-1.9, 1.7, -1.5)))
plot(ts.sim_MA3, main = "Simulated MA(3) Process", col = "blue")
acf(ts.sim_MA3, main = "ACF of MA(3) Process")
pacf(ts.sim_MA3, main = "PACF of MA(3) Process")
```

### MA(4)
```{r}
ts.sim_MA4 <- arima.sim(n = 10000, list(ma = c(-1.9, 1.7, -1.5, 1.5)))
plot(ts.sim_MA4, main = "Simulated MA(4) Process", col = "blue")
acf(ts.sim_MA4, main = "ACF of MA(4) Process")
pacf(ts.sim_MA4, main = "PACF of MA(4) Process")
```